### ISSUE TITLE
Adding tag on an already indented text node force the whole line to change indentation (if not the one "expected")

### ISSUE THREAD

**Issue by PMox** [chrisbra/vim-xml-ftplugin#12] opened 2019-07-14 16:47 UTC
**Describe the bug**
Adding an XML tag after some text is forcing the whole line to be gain an extra indent, while it should not.

**Repro steps**
1) `$vim file.xml`
2) `set ts=2; set sw=2; set et` (just to aligned in the repro)
3) insert `<root>`
4) insert a newline
5) start typing some text (**no** `<`)
- up to now no indent is added
6) type a `<tag>`
- when you type the `>` the whole line is indented, of **2** shiftwidth, including the text before the node

This is the code at step (5):

```
<root>
foo <tag
```

This is the code at (6):
```
<root>
    foo <tag>   # double indent here
```

Expected behaviour:

- do not change indentation if the new tag is not preceded by non-blanks
- anyway it must add a single shiftwidth, not 2

**Workaround**
Manually fix the indent, **but** if I continue typing and add a tag, then the indent is changed again on the same line (always of two shiftwidth).

**Comment by chrisbra** [comment] 2019-07-16 11:38
I believe this is a duplicate of #9

**Closed as completed by chrisbra** 2019-07-16 11:38 UTC
